name: CD Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cloud-infrastructure-test:latest .

      - name: Stop existing container
        shell: powershell
        run: |
          $container = docker ps -aq -f "name=^cloud-infrastructure-test$"

          if ($container) {
            docker stop cloud-infrastructure-test
            docker rm cloud-infrastructure-test
          } else {
            Write-Host "No existing container found. Continuing deployment."
          }

      - name: Run Docker container
        run: docker run -d --name cloud-infrastructure-test -p 8000:8000 cloud-infrastructure-test:latest

      - name: Verify Docker container
        run: docker ps